### PR TITLE
🛀🏻 - [CLEAN UP] - Remove un-needed .DS_Store file

### PR DESCRIPTION
**Pull request by sauconny**
## Pull Request Details
This pull request removes the un-needed `.DS_Store` files and adds them to the `.gitignore`. This file gets added for some reason on MacOSX, but this is now solved ✔️.

### CODE REVIEW

**Comment by eric-hc** [comment]
What's going on here?

**Comment by sauconny** [comment]
Stale PR....you just hate to see it 😓

**Comment by shmam** [comment]
smh I am still in school fool

**Comment by shmam** [comment]
also why was there three commits just to remove a .DS_Store file 🤨

**Review by shmam — APPROVED** [review]
Thank you sir! Looks great

**Pull request merged**
